name = "MendelLocationScores"
desc = "MendelLocationScores; part of the OpenMendel project."
uuid = "03b2b2e3-a3dd-5f5d-a4ee-4faf5700023a"
version = "0.5.0"
license = "MIT"
authors = ["Kenneth Lange <klange@ucla.edu>", "Eric Sobel <esobel@ucla.edu>", "OpenMendel Team"]
keywords = ["OpenMendel", "location scores", "linkage"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MendelBase = "4fb2d825-8540-5432-a3a3-b9ff66df2cb5"
MendelSearch = "4fa469e6-9890-5c68-874e-584f43f9cdde"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
